<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>keyEquivalent</key>
	<string>^~D</string>
	<key>name</key>
	<string>HTML (Tornado)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Since html is valid in Tornado templates include the html patterns</string>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>{#</string>
			<key>end</key>
			<string>#}</string>
			<key>name</key>
			<string>comment.line.django.template</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>{{</string>
			<key>end</key>
			<string>}}</string>
			<key>name</key>
			<string>meta.tag.template.variable.django.template</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[\S&amp;&amp;[^}]]+</string>
					<key>name</key>
					<string>variable.other.readwrite.django.template</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>({%)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.django.tagbraces</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(%})</string>
			<key>name</key>
			<string>meta.scope.django.template.tag</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(apply|comment|from|import|module|try|except|finally|while|end|with|block|extends|for|if|include|else|elif|escape|autoescape|urlescape|xhtml_escape|raw|set|xsrf_form_html|json_encode|squeeze|whitespace|static_url|and|or|not|in|by|as)\b</string>
					<key>name</key>
					<string>keyword.control.django.template</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[a-zA-Z_]+</string>
					<key>name</key>
					<string>string.unquoted.django.template.tag</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.django</string>
	<key>uuid</key>
	<string>F4B0A70C-ECF6-4660-BC26-785216E3CF02</string>
</dict>
</plist>
